title: Blog of youth and passion
author: Teenyee Zeng
email: 326640559@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage


collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "sortByCategory"  #分类页使用的样式
  -
    scope:
      path: ""
      type: "tags"
    values:
      layout: "sortByCategory"  #分类页使用的样式

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Teenyee Zeng
  tagline: Java Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation:
    - title: 首页
      url: /
    - title: 一篇就够
      url: /tagSort/one-post-enough/
    - title: 项目日记
      url: /tagSort/project-diary/
    - title: 阅读笔记
      url: /tagSort/reading-note/
  # generate social links in footer
  social_links:
    github:  imZTY
    zhihu: luo-ri-han-qiu-shuang
    music163: 372473891
#    jianshu: 7dcd38acf498
    yuque: imzty
    # twitter: thelehhman
    # linkedIn: in/thelehhman
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll # githubPage need this


plugins:
  - jekyll-seo-tag
#  - jekyll-feed

# Gitalk settings
comment_gitalk_clientId: b4da5856fb7887b66c79
comment_gitalk_clientSecret: da26529e26539b1b6b344f7bb37cfe3c94731bb6
comment_gitalk_repo: imzty.github.io
github_username: imzty

